<?php
namespace TaxCloud\Tests;

use TaxCloud\Request\AddExemptCertificate;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-21 at 18:50:43.
 */
class AddExemptCertificateTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AddExemptCertificate
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AddExemptCertificate;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers TaxCloud\Request\AddExemptCertificate::setExemptCert
     * @todo   Implement testSetExemptCert().
     */
    public function testSetExemptCert()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
