<?php
namespace TaxCloud\Tests;

use TaxCloud\Address;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-21 at 18:51:27.
 */
class AddressTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Address
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Address;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers TaxCloud\Address::getAddress2
     * @todo   Implement testGetAddress2().
     */
    public function testGetAddress2()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\Address::setZip5
     * @todo   Implement testSetZip5().
     */
    public function testSetZip5()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\Address::setZip4
     * @todo   Implement testSetZip4().
     */
    public function testSetZip4()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\Address::getZip
     * @todo   Implement testGetZip().
     */
    public function testGetZip()
    {
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }
}
