<?php
namespace TaxCloud\Tests;

use TaxCloud\Request\Authorized;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-21 at 18:51:36.
 */
class AuthorizedTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Authorized
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Authorized;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers TaxCloud\Authorized::setApiLoginID
     * @todo   Implement testSetApiLoginID().
     */
    public function testSetApiLoginID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\Authorized::getApiLoginID
     * @todo   Implement testGetApiLoginID().
     */
    public function testGetApiLoginID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\Authorized::setApiKey
     * @todo   Implement testSetApiKey().
     */
    public function testSetApiKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\Authorized::getApiKey
     * @todo   Implement testGetApiKey().
     */
    public function testGetApiKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\Authorized::setCustomerID
     * @todo   Implement testSetCustomerID().
     */
    public function testSetCustomerID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\Authorized::getCustomerID
     * @todo   Implement testGetCustomerID().
     */
    public function testGetCustomerID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\Authorized::setCartID
     * @todo   Implement testSetCartID().
     */
    public function testSetCartID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\Authorized::getCartID
     * @todo   Implement testGetCartID().
     */
    public function testGetCartID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\Authorized::setCartItems
     * @todo   Implement testSetCartItems().
     */
    public function testSetCartItems()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\Authorized::getCartItems
     * @todo   Implement testGetCartItems().
     */
    public function testGetCartItems()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\Authorized::setOrderID
     * @todo   Implement testSetOrderID().
     */
    public function testSetOrderID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\Authorized::getOrderID
     * @todo   Implement testGetOrderID().
     */
    public function testGetOrderID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\Authorized::setAuthorizedDate
     * @todo   Implement testSetAuthorizedDate().
     */
    public function testSetAuthorizedDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\Authorized::getAuthorizedDate
     * @todo   Implement testGetAuthorizedDate().
     */
    public function testGetAuthorizedDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
