<?php

namespace TaxCloud\Tests;

use TaxCloud\CartItem;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-21 at 18:52:40.
 */
class CartItemTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CartItem
     */
    protected $_cartitem;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
      $this->_cartitem = new CartItem(
        '123',
        'ABC123',
        '00000',
        '12.34',
        '1'
      );
    }

    public function testGetIndex()
    {
      $this->assertEquals('123', $this->_cartitem->getIndex());
    }

    public function testGetItemID()
    {
      $this->assertEquals('ABC123', $this->_cartitem->getItemID());
    }

    public function testGetTIC()
    {
      $this->assertEquals('00000', $this->_cartitem->getTIC());
    }

    public function testGetPrice()
    {
      $this->assertEquals('12.34', $this->_cartitem->getPrice());
    }

    public function testGetQty()
    {
      $this->assertEquals('1', $this->_cartitem->getQty());
    }
}
