<?php
namespace TaxCloud;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-21 at 18:53:11.
 */
class ExemptStateTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ExemptState
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ExemptState;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers TaxCloud\ExemptState::getStateAbbr
     * @todo   Implement testGetStateAbbr().
     */
    public function testGetStateAbbr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\ExemptState::getReasonForExemption
     * @todo   Implement testGetReasonForExemption().
     */
    public function testGetReasonForExemption()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\ExemptState::getIdentificationNumber
     * @todo   Implement testGetIdentificationNumber().
     */
    public function testGetIdentificationNumber()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
