<?php
namespace TaxCloud;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-21 at 18:53:22.
 */
class ExemptionCertificateDetailTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ExemptionCertificateDetail
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ExemptionCertificateDetail;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers TaxCloud\ExemptionCertificateDetail::construct
     * @todo   Implement testConstruct().
     */
    public function testConstruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\ExemptionCertificateDetail::getExemptStates
     * @todo   Implement testGetExemptStates().
     */
    public function testGetExemptStates()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\ExemptionCertificateDetail::getSinglePurchase
     * @todo   Implement testGetSinglePurchase().
     */
    public function testGetSinglePurchase()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\ExemptionCertificateDetail::getSinglePurchaseOrderNumber
     * @todo   Implement testGetSinglePurchaseOrderNumber().
     */
    public function testGetSinglePurchaseOrderNumber()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\ExemptionCertificateDetail::getPurchaserFirstName
     * @todo   Implement testGetPurchaserFirstName().
     */
    public function testGetPurchaserFirstName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\ExemptionCertificateDetail::getPurchaserLastName
     * @todo   Implement testGetPurchaserLastName().
     */
    public function testGetPurchaserLastName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\ExemptionCertificateDetail::getPurchaserTitle
     * @todo   Implement testGetPurchaserTitle().
     */
    public function testGetPurchaserTitle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\ExemptionCertificateDetail::getPurchaserAddress1
     * @todo   Implement testGetPurchaserAddress1().
     */
    public function testGetPurchaserAddress1()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\ExemptionCertificateDetail::getPurchaserAddress2
     * @todo   Implement testGetPurchaserAddress2().
     */
    public function testGetPurchaserAddress2()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\ExemptionCertificateDetail::getPurchaserCity
     * @todo   Implement testGetPurchaserCity().
     */
    public function testGetPurchaserCity()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\ExemptionCertificateDetail::getPurchaserState
     * @todo   Implement testGetPurchaserState().
     */
    public function testGetPurchaserState()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\ExemptionCertificateDetail::getPurchaserZip
     * @todo   Implement testGetPurchaserZip().
     */
    public function testGetPurchaserZip()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\ExemptionCertificateDetail::getPurchaserTaxID
     * @todo   Implement testGetPurchaserTaxID().
     */
    public function testGetPurchaserTaxID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\ExemptionCertificateDetail::getPurchaserBusinessType
     * @todo   Implement testGetPurchaserBusinessType().
     */
    public function testGetPurchaserBusinessType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\ExemptionCertificateDetail::getPurchaserBusinessTypeOtherValue
     * @todo   Implement testGetPurchaserBusinessTypeOtherValue().
     */
    public function testGetPurchaserBusinessTypeOtherValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\ExemptionCertificateDetail::getPurchaserExemptionReason
     * @todo   Implement testGetPurchaserExemptionReason().
     */
    public function testGetPurchaserExemptionReason()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\ExemptionCertificateDetail::getPurchaserExemptionReasonValue
     * @todo   Implement testGetPurchaserExemptionReasonValue().
     */
    public function testGetPurchaserExemptionReasonValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\ExemptionCertificateDetail::getCreatedDate
     * @todo   Implement testGetCreatedDate().
     */
    public function testGetCreatedDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
