<?php
namespace TaxCloud;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-21 at 18:54:37.
 */
class GetTICsRspTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var GetTICsRsp
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new GetTICsRsp;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers TaxCloud\GetTICsRsp::getTICs
     * @todo   Implement testGetTICs().
     */
    public function testGetTICs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
