<?php
namespace TaxCloud\Tests;

use TaxCloud\Request\Lookup;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-21 at 18:54:43.
 */
class LookupTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Lookup
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Lookup;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers TaxCloud\Lookup::getApiLoginID
     * @todo   Implement testGetApiLoginID().
     */
    public function testGetApiLoginID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\Lookup::getApiKey
     * @todo   Implement testGetApiKey().
     */
    public function testGetApiKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\Lookup::getCustomerID
     * @todo   Implement testGetCustomerID().
     */
    public function testGetCustomerID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\Lookup::getCartID
     * @todo   Implement testGetCartID().
     */
    public function testGetCartID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\Lookup::getCartItems
     * @todo   Implement testGetCartItems().
     */
    public function testGetCartItems()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\Lookup::getOrigin
     * @todo   Implement testGetOrigin().
     */
    public function testGetOrigin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\Lookup::getDestination
     * @todo   Implement testGetDestination().
     */
    public function testGetDestination()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\Lookup::getDeliveredBySeller
     * @todo   Implement testGetDeliveredBySeller().
     */
    public function testGetDeliveredBySeller()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
