<?php
namespace TaxCloud\Tests;

use TaxCloud\Request\LookupForDate;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-21 at 18:54:46.
 */
class LookupForDateTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var LookupForDate
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new LookupForDate;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers TaxCloud\LookupForDate::getApiLoginID
     * @todo   Implement testGetApiLoginID().
     */
    public function testGetApiLoginID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\LookupForDate::getApiKey
     * @todo   Implement testGetApiKey().
     */
    public function testGetApiKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\LookupForDate::getCustomerID
     * @todo   Implement testGetCustomerID().
     */
    public function testGetCustomerID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\LookupForDate::getCartID
     * @todo   Implement testGetCartID().
     */
    public function testGetCartID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\LookupForDate::getCartItems
     * @todo   Implement testGetCartItems().
     */
    public function testGetCartItems()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\LookupForDate::getOrigin
     * @todo   Implement testGetOrigin().
     */
    public function testGetOrigin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\LookupForDate::getDestination
     * @todo   Implement testGetDestination().
     */
    public function testGetDestination()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\LookupForDate::getDeliveredBySeller
     * @todo   Implement testGetDeliveredBySeller().
     */
    public function testGetDeliveredBySeller()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\LookupForDate::getExemptCert
     * @todo   Implement testGetExemptCert().
     */
    public function testGetExemptCert()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\LookupForDate::getUseDate
     * @todo   Implement testGetUseDate().
     */
    public function testGetUseDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
