<?php
namespace TaxCloud\Tests;

use TaxCloud\Request\Ping;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-21 at 18:55:13.
 */
class PingTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Ping
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Ping;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers TaxCloud\Ping::getApiLoginID
     * @todo   Implement testGetApiLoginID().
     */
    public function testGetApiLoginID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\Ping::getApiKey
     * @todo   Implement testGetApiKey().
     */
    public function testGetApiKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
