<?php
namespace TaxCloud;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-21 at 18:55:27.
 */
class ResponseBaseTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ResponseBase
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ResponseBase;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers TaxCloud\ResponseBase::getResponseType
     * @todo   Implement testGetResponseType().
     */
    public function testGetResponseType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\ResponseBase::getMessages
     * @todo   Implement testGetMessages().
     */
    public function testGetMessages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
