<?php
namespace TaxCloud;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-21 at 18:55:32.
 */
class ResponseMessageTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ResponseMessage
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ResponseMessage;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers TaxCloud\ResponseMessage::getResponseType
     * @todo   Implement testGetResponseType().
     */
    public function testGetResponseType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\ResponseMessage::getMessage
     * @todo   Implement testGetMessage().
     */
    public function testGetMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
