<?php
namespace TaxCloud;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-21 at 18:56:11.
 */
class TaxIDTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TaxID
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TaxID;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers TaxCloud\TaxID::getTaxType
     * @todo   Implement testGetTaxType().
     */
    public function testGetTaxType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\TaxID::getIDNumber
     * @todo   Implement testGetIDNumber().
     */
    public function testGetIDNumber()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\TaxID::getStateOfIssue
     * @todo   Implement testGetStateOfIssue().
     */
    public function testGetStateOfIssue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
