<?php
namespace TaxCloud;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-21 at 18:55:57.
 */
class TICGroupTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TICGroup
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TICGroup;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers TaxCloud\TICGroup::getGroupID
     * @todo   Implement testGetGroupID().
     */
    public function testGetGroupID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TaxCloud\TICGroup::getDescription
     * @todo   Implement testGetDescription().
     */
    public function testGetDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
